In [7]:
import os #cmd line library
#\\ is a windows thing, on linux paths are /
data_folder = "C:\Users\story645\Desktop\gcdrb_sessions\data"
print(data_folder)
data_path = os.path.join(data_folder, 'nyc_2005_2015.csv')
print(data_path)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-7-59e3b40fb889>, line 3)

In [8]:
import os #cmd line library
#fix unicode escape error by replacing \ with \\ 
#is a windows thing, on linux paths are /
data_folder = "C:\\Users\\story645\\Desktop\\gcdrb_sessions\\data"
print(data_folder)
data_path = os.path.join(data_folder, 'nyc_2005_2015.csv')
print(data_path)

C:\Users\story645\Desktop\gcdrb_sessions\data
C:\Users\story645\Desktop\gcdrb_sessions\data\nyc_2005_2015.csv


In [6]:
import pandas as pd
weather = pd.read_csv(data_path)

In [11]:
weather.head(2)

STATION_NAME      DATE  EMXP  MXSD  \
0  NEW YORK J F KENNEDY INTERNATIONAL AIRPORT NY US  20050601   152     0   
1  NEW YORK J F KENNEDY INTERNATIONAL AIRPORT NY US  20050701   439     0   

   TPCP  TSNW  EMXT  EMNT  MMXT  MMNT  MNTM  
0   528     0   350   117   260   173   217  
1  1324     0   333   161   283   205   244

In [17]:
print(weather['TSNW'].max())
print(weather['TSNW'].mean())

1023
-1833.0578461538462


In [18]:
weather['TSNW'].describe()

count    1625.000000
mean    -1833.057846
std      3928.840691
min     -9999.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      1023.000000
Name: TSNW, dtype: float64

In [20]:
import numpy as np

In [21]:
1>2

False

In [23]:
b = np.array(([[1,2,3],[4,5,6],[7,8,9]]))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b>2 #boolean mask

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [25]:
b[b>2]

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
(weather==-9999.)

STATION_NAME   DATE   EMXP   MXSD   TPCP   TSNW   EMXT   EMNT   MMXT  \
0           False  False  False  False  False  False  False  False  False   
1           False  False  False  False  False  False  False  False  False   
2           False  False  False  False  False  False  False  False  False   
3           False  False  False  False  False  False  False  False  False   
4           False  False  False  False  False  False  False  False  False   
5           False  False  False  False  False  False  False  False  False   
6           False  False  False  False  False  False  False  False  False   
7           False  False  False  False  False  False  False  False  False   
8           False  False  False  False  False  False  False  False  False   
9           False  False  False  False  False  False  False  False  False   
10          False  False  False  False  False  False  False  False  False   
11          False  False  False  False  False  False  False  False  False   
12          False  False  False  False  False  False  False  False  False   
13          False  False  False  False  False  False  False  False  False   
14          False  False  False  False  False  False  False  False  False   
15          False  False  False  False  False  False  False  False  False   
16          False  False  False  False  False  False  False  False  False   
17          False  False  False  False  False  False  False  False  False   
18          False  False  False  False  False  False  False  False  False   
19          False  False  False  False  False  False  False  False  False   
20          False  False  False  False  False  False  False  False  False   
21          False  False  False  False  False  False  False  False  False   
22          False  False  False  False  False  False  False  False  False   
23          False  False  False  False  False  False  False  False  False   
24          False  False  False  False  False  False  False  False  False   
25          False  False  False  False  False  False  False  False  False   
26          False  False  False  False  False  False  False  False  False   
27          False  False  False  False  False  False  False  False  False   
28          False  False  False  False  False  False  False  False  False   
29          False  False  False  False  False  False  False  False  False   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
1595        False  False  False  False  False  False  False  False  False   
1596        False  False  False  False  False  False  False  False  False   
1597        False  False  False  False  False  False  False  False  False   
1598        False  False  False  False  False  False  False  False  False   
1599        False  False  False   True  False   True  False  False  False   
1600        False  False  False   True  False   True  False  False  False   
1601        False  False  False   True  False   True  False  False  False   
1602        False  False  False  False  False  False  False  False  False   
1603        False  False  False  False  False  False  False  False  False   
1604        False  False  False  False  False  False  False  False  False   
1605        False  False  False  False  False  False  False  False  False   
1606        False  False  False  False  False  False  False  False  False   
1607        False  False  False  False  False  False  False  False  False   
1608        False  False  False  False  False  False  False  False  False   
1609        False  False  False  False  False  False  False  False  False   
1610        False  False  False  False  False  False  False  False  False   
1611        False  False  False  False  False  False  False  False  False   
1612        False  False  False  False  False  False  False  False  False   
1613        False  False  False  False  False  False  False  False  False   
1614        False  False  False  False  False  False  False  False  False   
1